name: kara_defter
description: Alacak borç takip uygulaması - Kara Defter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  
  # Database
  sqflite: ^2.4.2
  path: ^1.9.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^8.2.0
  
  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
